# https://docs.docker.com/compose/compose-file/
version: '3.7'
services:
  olivetree:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ecto://olivetree:olivetree@postgres/olivetree
      HOSTNAME: localhost
      PORT: 80
      # mix phx.gen.secret
      SECRET_KEY_BASE: fzBk8OEcI8thGxlypWPUqfR2w2WopdN8v8pmpuy2JNj2eerbYFnlecuVMrFPGYnW
    labels:
      - "traefik.frontend.rule=Host:api.olivetree.app"
      - "traefik.frontend.entryPoints=http,https"

  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: olivetree
      POSTGRES_PASSWORD: olivetree
      POSTGRES_USER: olivetree
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

networks:
  default:
    external:
      name: web
